### ISSUE TITLE
Duplicate method in Deals class

### ISSUE THREAD

**Issue by choiceforyou** [TTRGroup/pipedrive-api-php#8]
Compile Error: Cannot redeclare Benhawker\Pipedrive\Library\Deals::addProduct() in 
/vendor/benhawker/pipedrive/src/Benhawker/Pipedrive/Library/Deals.php line 126

**Comment by kticka** [comment]
Bump

**Comment by stephanvierkant** [comment]
@choiceforyou @kticka I think the repo owner isn't very active here. Maybe we can fork the repo?

**Comment by choiceforyou** [comment]
I have already forked the repo here, https://github.com/choiceforyou/pipedrive-api-php

Will wait for another weekend and if still does not see any activity from author, will spin out new repo to continue development on lib.

**Comment by kticka** [comment]
Sure, I would join. ;)

**Comment by benhawker1** [comment]
done sorry for the deal

**Comment by choiceforyou** [comment]
Thanks, keep up good work.
